- name: "Set hostname"
  hostname:
    name: "{{ inventory_hostname }}"
  when: not (ansible_hostname == inventory_hostname)

- name: "Ensure necessary packages are installed"
  apt:
    name: "{{ base_pkgs }}"
    state: present
    update_cache: yes

- name: "Check to make sure we have a 'pipeset' group"
  group:
    name: pipeset
    state: present

- name: Add local public key for key-based SSH authentication
  authorized_key:
    user: "{{ sudoer_user_name }}"
    key: "{{item}}"
  with_file:
    - ~/.ssh/id_ed25519.pub

- name: Restrict root SSH logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Restrict SSH logins to keys only
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Restart sshd
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd

