lvm_groups:
  - vgname: data
    disks:
      - /dev/nvme1n1
    create: true
    lvnames:
      - lvname: app
        size: 10G
        create: true
        filesystem: ext4
        mount: true
        mntp: "{{ apps_dir }}"
      - lvname: data
        size: 100%FREE
        create: true
        filesystem: ext4
        mount: true
        mntp: "{{ data_dir }}"
