---
- hosts: brokers


- hosts: schema_registries
  become: yes
  vars:
    manage_lvm: true
    data_dir: "/data"
    apps_dir: "/opt"
    registry_kafka_servers:  "{{ groups['brokers']
      | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
      | join(':9092,') }}:9092"

  vars_files:
    - lvm-schema_registries.yml
    - pipeset_users.yml

  roles:
    - base
    - mrlesmithjr.manage-lvm
    - geerlingguy.docker
    - add-accounts
    - role: git-deploy
      repo_url: "git+ssh://git@dbms/home/git/kafka-docker-images.git"
      repo_app_dir: "schema_registry"
      repo_version: "2.8"
      app_dir: "/opt/schema_registry"

