- name: set kernel parameters
  vars:
    sysctl_config:
      net.core.somaxconn: 4096
      net.ipv4.tcp_max_syn_backlog: 4096
      net.ipv4.tcp_keepalive_time: 120
      net.ipv4.tcp_keepalive_intvl: 30
      net.ipv4.tcp_fin_timeout: 30
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: 'present'
    sysctl_set: yes
    reload: yes
    ignoreerrors: yes
  with_dict: "{{ sysctl_config }}"

# Settings for
# [aws ubuntu 18.04, suggest 1, suggest 2]
#
# net.core.somaxconn: 128,3240000,4096,65536
# net.ipv4.tcp_max_syn_backlog: 256,3240000,4096,65536
# net.ipv4.tcp_keepalive_time: 7200,120,300
# net.ipv4.tcp_keepalive_intvl: 75,,30,30,15
# net.ipv4.tcp_fin_timeout: 60,,30
# net.nf_conntrack_max: 262144,,250000,1048576
